version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    dns:
      - 8.8.8.8
      - 8.8.4.4

  backend:
    build: ./ConsultantPlatform
    restart: always
    environment:
      ConnectionStrings:DefaultConnection: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      ASPNETCORE_URLS: http://+:80
    expose:
      - "80"
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/youmentor.ru:/etc/letsencrypt/live/youmentor.ru:ro
      - /etc/letsencrypt/archive/youmentor.ru:/etc/letsencrypt/archive/youmentor.ru:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db_data: