version: '3.8'

services:
  # --- Сервис Базы Данных PostgreSQL ---
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports: # Опционально, если нужен доступ с хоста
    #   - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Сервис Бэкенда ASP.NET ---
  backend:
    build: ./ConsultantPlatform # Указываем на вашу папку с бэкендом
    restart: always
    environment:
      ConnectionStrings:DefaultConnection: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      # Другие переменные окружения для бэкенда, если есть
    expose:
      - "80" # Бэкенд слушает на порту 80
    depends_on:
      db:
        condition: service_healthy # Ждем, пока БД будет готова

  # --- Сервис Веб-сервера Nginx ---
  nginx:
    build: ./nginx # Указываем на папку с конфигом Nginx
    restart: always
    ports:
      - "80:80" # Пробрасываем порт 80 с хоста
    depends_on:
      - backend # Зависим от бэкенда

# --- Определение томов ---
volumes:
  db_data: